# Soal 1
Buatlah fungsi-fungsi pemecah (solver) akar-akar persamaan nonlinear menggunakan bahasa Python dan ditulis dalam sel-sel Jupyter Notebook (bisa via Google Colab maupun VS Code) mencakup 4 metode yang dipelajari di kelas (Bisection, Regula Falsi, Secant, dan Newton-Raphson). Contoh penamaan fungsinya dalam blok fungsi def di Python: (1) bisection, (2) regulafalsi, (3) secant, (4) newtonrap

In [ ]:
def f(x):
  return x**2 - x - 2
def df(x):
  return 2*x - 1

In [ ]:
def bisection(f, a, b, tol=1e-6):

  while abs(b-a) > tol:
      c = (a+b)/2

      if f(a)*f(c) < 0:
          b = c
      else:
        a = c

  return (a+b)/2

In [ ]:
def regulafalsi(f, a, b, tol=1e-6):

    c = a

    while abs(f(c)) > tol:
      c = b - (f(b)*(b-a))/(f(b)-f(a))

      if f(a)*f(c) < 0:
          b = c
      else:
          a = c

    return c

In [ ]:
def secant(f, x0, x1, tol=1e-6):

    while abs(x1-x0) > tol:
        x2 = x1 - f(x1)*(x1-x0)/(f(x1)-f(x0))
        x0 = x1
        x1 = x2

    return x1

In [ ]:
def newtonrap(f, df, x0, tol=1e-6):

    x1 = x0

    while abs(f(x1)) > tol:
      x1 = x1 - f(x1)/df(x1)

    return x1

# Soal 2
Setelah pendefinisian fungsi-fungsi tersebut, panggil semuanya (masing-masing) untuk memecahkan f(x) = x2 - x - 2 = 0.

In [ ]:
akar_bisection = bisection(f,1,3)
akar_regulafalsi = regulafalsi(f,1,3)
akar_secant = secant(f,1,3)
akar_newton = newtonrap(f,df,3)

print("Hasil Perhitungan Akar Persamaan f(x) = x^2 - x - 2")
print("---------------------------------------------------")
print("Metode Bisection       :", akar_bisection)
print("Metode Regula Falsi    :", akar_regulafalsi)
print("Metode Secant          :", akar_secant)
print("Metode Newton Raphson  :", akar_newton)

Hasil Perhitungan Akar Persamaan f(x) = x^2 - x - 2
---------------------------------------------------
Metode Bisection       : 2.999999523162842
Metode Regula Falsi    : 1.9999999105930355
Metode Secant          : 2.0
Metode Newton Raphson  : 2.000000000698492

# Soal 3
 Baca dan pahami dua materi pengayaan berikut ini,
https://github.com/artnugraha/komputasi-numerik/blob/main/Modul03/03-1-metode-bagi-dua.ipynb
https://github.com/artnugraha/komputasi-numerik/blob/main/Modul03/03-2-metode-newton.ipynb
Kemudian, di bagian akhir dari dua links di atas (scroll ke bagian bawahnya), kita dapat melihat adanya proses iterasi untuk menuju konvergensi dari setiap metode. Buatlah tabel proses iterasi serupa itu untuk metode regulafalsi dan metode secant dengan menggunakan kode Python yang sesuai.

In [ ]:
import pandas as pd

In [ ]:
def regulafalsi_iterasi(f, a, b, tol=1e-6, max_iter=10):

    data = []
    for i in range(max_iter):
        c = b - (f(b)*(b-a))/(f(b)-f(a))

        data.append([i+1, a, b, c, f(c)])

        if abs(f(c)) < tol:
          break

        if f(a)*f(c) < 0:
          b = c
        else:
          a = c

    tabel = pd.DataFrame(data, columns=["Iterasi", "a", "b", "c", "f(c)"])
    return tabel

In [ ]:
def secant_iterasi(f, x0, x1, tol=1e-6, max_iter=10):

  data = []

  for i in range(max_iter):

      x2 = x1 - f(x1)*(x1-x0)/(f(x1)-f(x0))

      data.append([i+1, x0, x1, x2, f(x2)])

      if abs(x2-x1) < tol:
        break

  tabel = pd.DataFrame(data,columns=["iterasi", "x0", "x1", "x2", "f(x2)"])
  return tabel

In [ ]:
print("TABEL ITERASI METODE REGULA FALSI")

display(
    regulafalsi_iterasi(f,1,3)
    .style
    .set_table_styles([
        dict(selector="th", props=[("text-align","center")]),
        dict(selector="td", props=[("text-align","center")])
    ])
    .hide(axis="index")
)

print("\n\nTABEL ITERASI METODE SECANT")

display(
    secant_iterasi(f,1,3)
    .style
    .set_table_styles([
        dict(selector="th", props=[("text-align","center")]),
        dict(selector="td", props=[("text-align","center")])
    ])
    .hide(axis="index")
)

TABEL ITERASI METODE REGULA FALSI

TABEL ITERASI METODE SECANT

# Soal 4
Carilah satu masalah fisika sederhana (seperti contoh penentuan waktu untuk mencapai tinggi benda pada kinematika gerak vertikal) dan pecahkan dengan salah satu metode pencarian akar persamaan nonlinear dalam bahasa Python.

In [ ]:
# fungsi persamaan
def f(t):
    return 2*t**2 - 20

# turunan fungsi
def df(t):
    return 4*t

# metode Newton-Raphson
def newtonrap(f, df, x0, tol=1e-6):

    while abs(f(x0)) > tol:
        x0 = x0 - f(x0)/df(x0)

    return x0

# tebakan awal
akar = newtonrap(f, df, 2)

print("Waktu yang dibutuhkan benda =", akar, "detik")

Waktu yang dibutuhkan benda = 3.1622776604441363 detik

# Soal 5
Ada metode-metode pencarian akar persamaan nonlinear lainnya yang tidak kita bahas di kelas, salah satunya adalah metode fixed-point iteration (iterasi titik tetap). Pelajari metode ini dari sumber buku teks maupun internet, buatlah pendefinisian fungsinya dalam satu sel di Jupyter Notebook dan kembali gunakan untuk mencari akar dari f(x) = x2 - x - 2 = 0.

In [ ]:
import math

def fixedpoint(g, x0, tol=1e-6):

  x1 = g(x0)

  while abs(x1 - x0) > tol:
    x0 = x1
    x1 = g(x0)

  return x1

In [ ]:
def g(x):
  return math.sqrt(x + 2)

In [ ]:
akar = fixedpoint(g, 1)

print(f"Akar persamaan f(x) =  x^2 - x -2 adalah {akar: .2f}")

Akar persamaan f(x) =  x^2 - x -2 adalah  2.00